theme: jekyll-theme-minimal
title: My Personal Website
description: A simple template based on minimal jekyll theme
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: Syntax
    url: syntax
  - title: Example
    url: example
  - title: Resume
    url: assets/files/sample_resume.pdf
  - title: Crab
    url: test
  - title: jello
  url: deer.jpeg

